spring:
  application:
    name: 'user-service-api'
  data:
    mongodb:
      uri: 'mongodb+srv://help-desk-user:help-desk-user@cluster0.7av88.mongodb.net/helpdeskdb?retryWrites=true&w=majority&appName=Cluster0'
      auto-index-creation: true
springdoc:
  openapi:
    title: 'User Service Api '
    description: 'Component responsible for user management created on formação backEnd Expert'
    version: 1.0.0


